# -*- coding: utf-8 -*-
"""face_detection_stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1774fgPhVI6c3G2f5f-n6fxzVTSeEwPPI
"""

import argparse
import cv2
import os
import time
import logging
import numpy as np
import requests
from ultralytics import YOLO
import threading
from queue import Queue

# =====================================================
# CONFIGURAÇÕES
# =====================================================

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)

# Ordem de prioridade das fontes de vídeo.
#
# Suporte a dois fluxos de celular:
#
# 1) App "IP Webcam" / "IP Camera" (Android) ou "DroidCam"/"EpocCam" (iOS):
#    o próprio celular vira um servidor e expõe uma URL HTTP/RTSP direta.
#    -> use a URL mostrada na tela do app, ex: "http://192.168.1.100:8080/video"
#
# 2) App "Larix Broadcaster": o celular ENVIA (push) o vídeo via RTMP ou RTSP
#    para um servidor no PC (ex: MediaMTX). O Python então lê do PRÓPRIO PC,
#    não do IP do celular.
#    -> rode o MediaMTX no PC (porta 8554 RTSP / 1935 RTMP)
#    -> configure no Larix: rtmp://IP_DO_PC:1935/live/cam (ou rtsp://IP_DO_PC:8554/cam)
#    -> aqui no Python, use o endereço RTSP local do MediaMTX:
#       "rtsp://127.0.0.1:8554/live/cam"
#
# Importante: cv2.VideoCapture lê RTMP/RTSP, mas não consegue "receber" um
# push do Larix diretamente — por isso o MediaMTX é necessário como
# intermediário no fluxo do Larix.
STREAM_URLS = [
    "http://192.168.1.100:8080/video",      # IP Webcam / IP Camera (ajuste o IP do celular)
    "rtsp://127.0.0.1:8554/live/cam",       # Larix -> MediaMTX (RTSP local, recomendado)
    "rtmp://127.0.0.1:1935/live/cam",       # Larix -> MediaMTX (lendo via RTMP, alternativa)
    "rtsp://192.168.1.100:8554/stream",     # RTSP genérico (ex: outro app/câmera IP real)
]

# Permite sobrescrever via variável de ambiente STREAM_URL ou --url na CLI,
# sem precisar editar o código a cada vez que o IP do celular mudar.
_env_url = os.environ.get("STREAM_URL")
if _env_url:
    STREAM_URLS.insert(0, _env_url)

# Webcams locais só são usadas como ÚLTIMO recurso (ver _connect_stream)
LOCAL_WEBCAM_IDS = [0, 1]

# Se True, tenta detectar automaticamente um IP Webcam na rede local
AUTO_DISCOVER_IP_WEBCAM = True

# Modelo YOLO para detecção facial
# Usa o modelo padrão YOLO e filtra por pessoas (classe 0)
MODEL_NAME = "yolov8n.pt"  # Nano - mais leve
# MODEL_NAME = "yolov8s.pt"  # Small - um pouco melhor
# MODEL_NAME = "yolov8m.pt"  # Medium - melhor performance

CONFIDENCE = 0.55
WINDOW_NAME = "Detecção Facial - Stream"
DISPLAY_WIDTH = 1280

# Diretório para salvar faces
SAVE_DIR = "faces"
SAVE_FACES = True
SAVE_COOLDOWN_SECONDS = 5

# Filtros
MIN_FACE_WIDTH = 60
MIN_FACE_HEIGHT = 60
BLUR_THRESHOLD = 80

# Performance
MAX_INFERENCE_FPS = 15
RECONNECT_DELAY = 2
CONNECT_TIMEOUT_PER_URL = 3  # segundos para testar cada URL

# =====================================================
# FUNÇÕES AUXILIARES
# =====================================================

def ensure_dir(path):
    """Cria diretório se não existir."""
    os.makedirs(path, exist_ok=True)

def variance_of_laplacian(image):
    """Calcula a variância do Laplaciano para detecção de borrão."""
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return cv2.Laplacian(gray, cv2.CV_64F).var()

def is_blurry(face_crop, threshold=BLUR_THRESHOLD):
    """Verifica se a imagem está borrada."""
    return variance_of_laplacian(face_crop) < threshold

def save_face(face_crop, track_id, confidence):
    """Salva o recorte facial com metadados."""
    ensure_dir(SAVE_DIR)
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(SAVE_DIR, f"face_id{track_id}_conf{confidence:.2f}_{timestamp}.jpg")
    cv2.imwrite(filename, face_crop)
    return filename

def resize_keep_ratio(frame, width):
    """Redimensiona mantendo a proporção."""
    h, w = frame.shape[:2]
    ratio = width / w
    return cv2.resize(frame, (width, int(h * ratio)))

def load_model():
    """Carrega o modelo YOLO."""
    log.info(f"📦 Carregando modelo: {MODEL_NAME}")
    try:
        model = YOLO(MODEL_NAME)
        log.info("✅ Modelo carregado com sucesso!")
        return model
    except Exception as e:
        log.error(f"❌ Erro ao carregar modelo: {e}")
        raise

# =====================================================
# GERENCIADOR DE STREAM
# =====================================================

class StreamManager:
    def __init__(self):
        self.cap = None
        self.cap_lock = threading.Lock()
        self.frame_queue = Queue(maxsize=2)
        self.running = False
        self.thread = None
        self.last_error = None

    def start(self):
        """Inicia o stream em uma thread separada."""
        self.running = True
        self.thread = threading.Thread(target=self._stream_worker, daemon=True)
        self.thread.start()

    # -------------------------------------------------
    # Descoberta / conexão
    # -------------------------------------------------

    def _try_open(self, source, backend=None, label=None):
        """Tenta abrir e validar uma fonte de vídeo (URL ou índice de webcam).
        Retorna o VideoCapture se funcionar, ou None."""
        label = label if label is not None else source
        log.info(f"🔍 Tentando: {label}")
        try:
            cap = cv2.VideoCapture(source, backend) if backend is not None else cv2.VideoCapture(source)
            if not cap.isOpened():
                cap.release()
                return None

            ret, frame = cap.read()
            if not ret or frame is None:
                cap.release()
                return None

            cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
            log.info(f"✅ Conectado a: {label}")
            return cap
        except Exception as e:
            log.warning(f"❌ Erro ao tentar {label}: {e}")
            return None

    def _discover_ip_webcam(self):
        """Tenta encontrar um IP Webcam ativo na rede local (portas comuns)."""
        for port in (8080, 8081, 8082, 8083):
            url = f"http://localhost:{port}/video"
            try:
                response = requests.get(url, timeout=1)
                if response.status_code == 200:
                    return url
            except requests.RequestException:
                continue
        return None

    def _connect_stream(self):
        """Tenta conectar, em ordem de prioridade:
        1) URLs configuradas em STREAM_URLS (IP Webcam / RTSP reais)
        2) IP Webcam descoberto automaticamente na rede
        3) Webcam local, como último recurso
        """
        # 1) URLs configuradas
        for url in STREAM_URLS:
            cap = self._try_open(url)
            if cap is not None:
                return cap

        # 2) Auto-descoberta de IP Webcam
        if AUTO_DISCOVER_IP_WEBCAM:
            discovered = self._discover_ip_webcam()
            if discovered:
                cap = self._try_open(discovered)
                if cap is not None:
                    return cap

        # 3) Webcam local — apenas como último recurso
        log.info("🔄 Nenhuma URL de rede funcionou. Tentando webcam local...")
        for cam_id in LOCAL_WEBCAM_IDS:
            cap = self._try_open(cam_id, label=f"webcam local (ID {cam_id})")
            if cap is not None:
                return cap

        raise RuntimeError("❌ Nenhuma fonte de vídeo disponível!")

    # -------------------------------------------------
    # Worker
    # -------------------------------------------------

    def _stream_worker(self):
        """Worker thread para capturar frames."""
        while self.running:
            try:
                with self.cap_lock:
                    needs_connect = self.cap is None or not self.cap.isOpened()
                if needs_connect:
                    new_cap = self._connect_stream()
                    with self.cap_lock:
                        self.cap = new_cap
                    continue

                with self.cap_lock:
                    cap = self.cap
                ret, frame = cap.read() if cap is not None else (False, None)

                if not ret or frame is None:
                    log.warning("⚠️ Stream perdido, reconectando...")
                    with self.cap_lock:
                        if self.cap is not None:
                            self.cap.release()
                        self.cap = None
                    time.sleep(RECONNECT_DELAY)
                    continue

                while self.frame_queue.qsize() >= 2:
                    try:
                        self.frame_queue.get_nowait()
                    except Exception:
                        break

                self.frame_queue.put(frame)

            except Exception as e:
                self.last_error = str(e)
                log.error(f"❌ Erro no stream: {e}")
                time.sleep(RECONNECT_DELAY)

    def get_frame(self, timeout=1):
        """Obtém o último frame da fila."""
        try:
            return self.frame_queue.get(timeout=timeout)
        except Exception:
            return None

    def stop(self):
        """Para o stream."""
        self.running = False
        if self.thread:
            self.thread.join(timeout=2)
        with self.cap_lock:
            if self.cap:
                self.cap.release()
                self.cap = None

# =====================================================
# PROCESSADOR DE DETECÇÃO
# =====================================================

class FaceDetector:
    def __init__(self, model):
        self.model = model
        self.frame_count = 0
        self.faces_detected_total = 0
        self.faces_saved_total = 0
        self.last_save_time = {}
        self.last_inference_time = 0
        self.cached_results = None
        self.fps = 0
        self.fps_counter = 0
        self.fps_timer = time.time()

    def process_frame(self, frame):
        """Processa um frame e retorna o frame anotado e informações."""
        self.frame_count += 1
        now = time.time()
        faces_in_frame = 0

        # Limita FPS de inferência
        run_inference = (now - self.last_inference_time) >= (1 / MAX_INFERENCE_FPS)
        if run_inference:
            self.last_inference_time = now
            self.cached_results = self.model.track(
                frame,
                persist=True,
                tracker="bytetrack.yaml",
                conf=CONFIDENCE,
                verbose=False
            )[0]

        results = self.cached_results

        # Processa detecções
        if results is not None and results.boxes is not None:
            for box in results.boxes:
                # Filtra apenas pessoas (classe 0)
                cls_id = int(box.cls[0])
                if cls_id != 0:
                    continue

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                face_w = x2 - x1
                face_h = y2 - y1

                if face_w < MIN_FACE_WIDTH or face_h < MIN_FACE_HEIGHT:
                    continue

                conf = float(box.conf[0])

                if hasattr(box, "id") and box.id is not None:
                    track_id = int(box.id.item())
                else:
                    track_id = -1

                face_crop = frame[
                    max(0, y1):min(frame.shape[0], y2),
                    max(0, x1):min(frame.shape[1], x2)
                ]

                if face_crop.size == 0:
                    continue

                faces_in_frame += 1
                self.faces_detected_total += 1

                # Desenha retângulo
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

                # Texto com ID e confiança
                label = f"ID {track_id} {conf:.2f}"
                cv2.putText(frame, label, (x1, y1 - 10),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

                # Salva a face
                if SAVE_FACES and not is_blurry(face_crop):
                    last_time = self.last_save_time.get(track_id, 0)
                    elapsed = now - last_time

                    if elapsed >= SAVE_COOLDOWN_SECONDS:
                        filename = save_face(face_crop, track_id, conf)
                        self.last_save_time[track_id] = now
                        self.faces_saved_total += 1
                        log.info(f"💾 Face salva: {filename}")

        # Atualiza FPS
        self.fps_counter += 1
        elapsed = time.time() - self.fps_timer
        if elapsed >= 1:
            self.fps = self.fps_counter / elapsed
            self.fps_counter = 0
            self.fps_timer = time.time()

        # Adiciona overlay de informações
        self._add_overlay(frame, faces_in_frame)

        return frame, faces_in_frame

    def _add_overlay(self, frame, faces_in_frame):
        """Adiciona overlay de informações no frame."""
        overlay = frame.copy()
        cv2.rectangle(overlay, (0, 0), (frame.shape[1], 120), (0, 0, 0), -1)
        cv2.addWeighted(overlay, 0.45, frame, 0.55, 0, dst=frame)

        infos = [
            f"FPS: {self.fps:.1f}",
            f"Faces no frame: {faces_in_frame}",
            f"Detecções totais: {self.faces_detected_total}",
            f"Faces salvas: {self.faces_saved_total}",
            f"Frame: {self.frame_count}",
            f"Modelo: {MODEL_NAME}"
        ]

        for i, txt in enumerate(infos):
            cv2.putText(frame, txt, (10, 20 + i * 20),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

    def reset_counters(self):
        """Reseta os contadores."""
        self.faces_detected_total = 0
        self.faces_saved_total = 0
        self.last_save_time = {}
        log.info("🔄 Contadores resetados!")

    def get_stats(self):
        """Retorna estatísticas do processamento."""
        return {
            'frames': self.frame_count,
            'detections': self.faces_detected_total,
            'saved': self.faces_saved_total,
            'fps': self.fps
        }

# =====================================================
# FUNÇÃO PRINCIPAL
# =====================================================

def parse_args():
    parser = argparse.ArgumentParser(description="Detecção facial com YOLO + stream")
    parser.add_argument(
        "--url", "-u",
        help="URL do stream de vídeo (ex: http://192.168.0.42:8080/video). "
             "Tem prioridade sobre STREAM_URL (env) e STREAM_URLS no código."
    )
    parser.add_argument(
        "--larix",
        action="store_true",
        help="Atalho para usar o fluxo Larix + MediaMTX local "
             "(equivalente a --url rtsp://127.0.0.1:8554/<caminho>). "
             "Use --mediamtx-path para trocar o caminho da stream."
    )
    parser.add_argument(
        "--mediamtx-path",
        default="live/cam",
        help="Caminho configurado no MediaMTX/Larix (padrão: live/cam). "
             "Só tem efeito junto com --larix."
    )
    return parser.parse_known_args()[0]


def main():
    args = parse_args()

    if args.larix:
        larix_url = f"rtsp://127.0.0.1:8554/{args.mediamtx_path}"
        STREAM_URLS.insert(0, larix_url)
        log.info(f"📱 Modo Larix ativado. Lendo do MediaMTX local: {larix_url}")
        log.info("   (confirme que o Larix está transmitindo para esse mesmo caminho)")

    if args.url:
        STREAM_URLS.insert(0, args.url)
        log.info(f"🔗 Usando URL passada por --url: {args.url}")

    print("="*60)
    print("   DETECÇÃO FACIAL COM YOLO + STREAM")
    print("="*60)

    # Carrega modelo
    print("\n📦 Carregando modelo YOLO...")
    model = load_model()

    # Inicia stream
    print("\n📡 Conectando ao stream...")
    stream = StreamManager()
    stream.start()
    time.sleep(2)

    # Verifica conexão
    test_frame = stream.get_frame(timeout=3)
    if test_frame is None:
        print("⚠️ Nenhum frame recebido ainda. Dicas:")
        print("   - Confirme que STREAM_URLS aponta para o IP correto do celular")
        print("   - No app IP Webcam/IP Camera, veja o IP exibido na tela inicial")
        print("   - Usando Larix? Confirme que o MediaMTX está rodando no PC")
        print("     e que o app está transmitindo para o mesmo caminho (ex: live/cam)")
        print("   - VDO.ninja (página web) NÃO funciona aqui — use IP Webcam/RTSP")
    else:
        print("✅ Stream conectado!")

    # Cria detector e janela
    detector = FaceDetector(model)
    cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_NORMAL)

    print("\n" + "="*60)
    print("🎯 DETECÇÃO EM EXECUÇÃO")
    print("   Pressione 'q' para sair")
    print("   Pressione 's' para salvar frame")
    print("   Pressione 'r' para resetar contadores")
    print("="*60 + "\n")

    try:
        while True:
            # Obtém frame
            frame = stream.get_frame(timeout=1)

            if frame is None:
                print("⏳ Aguardando frame...")
                continue

            # Processa frame
            processed_frame, _ = detector.process_frame(frame)

            # Exibe
            display = resize_keep_ratio(processed_frame, DISPLAY_WIDTH)
            cv2.imshow(WINDOW_NAME, display)

            # Controles
            key = cv2.waitKey(1) & 0xFF

            if key == ord('q'):
                print("\n🛑 Saindo...")
                break
            elif key == ord('s'):
                timestamp = time.strftime("%Y%m%d_%H%M%S")
                filename = f"frame_{timestamp}.jpg"
                cv2.imwrite(filename, frame)
                print(f"💾 Frame salvo: {filename}")
            elif key == ord('r'):
                detector.reset_counters()

    except KeyboardInterrupt:
        print("\n🛑 Interrompido pelo usuário.")

    finally:
        # Finalização
        stream.stop()
        cv2.destroyAllWindows()

        stats = detector.get_stats()
        print("\n" + "="*60)
        print("📊 RESUMO FINAL")
        print("="*60)
        print(f"Frames processados: {stats['frames']}")
        print(f"Total de detecções: {stats['detections']}")
        print(f"Faces salvas: {stats['saved']}")

        if stats['frames'] > 0:
            media_deteccoes_por_frame = stats['detections'] / stats['frames']
            print(f"Média de detecções por frame: {media_deteccoes_por_frame:.2f}")

        if stats['saved'] > 0:
            print(f"\n📁 Faces salvas em: {os.path.abspath(SAVE_DIR)}")

        print("="*60)
        print("✅ Processamento concluído!")

if __name__ == "__main__":
    main()

!pip install ultralytics